export enum ASSIGNMENT_TYPE {
  AUTO = 'AUTO',
  MANUAL = 'MANUAL',
}
export enum BANK_ACCOUNT_TYPE {
  SAVINGS = 'SAVINGS',
  CURRENT = 'CURRENT',
}
export enum BANK_VERIFICATION_STATUS {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  FAILED = 'FAILED',
}
export enum BOOKING_MODE {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
}
export enum BOOKING_PAYMENT_STATUS {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  REFUNDED = 'REFUNDED',
}
export enum BOOKING_STATUS {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  ENROUTE = 'ENROUTE',
  ARRIVED = 'ARRIVED',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
export enum CANCELLED_BY {
  CUSTOMER = 'CUSTOMER',
  PUROHIT = 'PUROHIT',
  ADMIN = 'ADMIN',
}
export enum CMS_CONTENT_TYPE {
  BANNER = 'BANNER',
  FAQ = 'FAQ',
  BLOG_ARTICLE = 'BLOG_ARTICLE',
  FESTIVAL_PROMOTION = 'FESTIVAL_PROMOTION',
}
export enum COMPLAINT_CATEGORY {
  SERVICE_NOT_PROVIDED = 'SERVICE_NOT_PROVIDED',
  LATE_ARRIVAL = 'LATE_ARRIVAL',
  BEHAVIOR_ISSUE = 'BEHAVIOR_ISSUE',
  PAYMENT_ISSUE = 'PAYMENT_ISSUE',
  QUALITY_ISSUE = 'QUALITY_ISSUE',
  TECHNICAL_ISSUE = 'TECHNICAL_ISSUE',
  ACCOUNT_ISSUE = 'ACCOUNT_ISSUE',
  GENERAL_QUERY = 'GENERAL_QUERY',
  OTHER = 'OTHER',
}
export enum COMPLAINT_STATUS {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED',
}
export enum CUSTOMER_PAYMENT_METHOD {
  CASH = 'CASH',
  ONLINE = 'ONLINE',
}
export enum DISCOUNT_TYPE {
  FLAT = 'FLAT',
  PERCENTAGE = 'PERCENTAGE',
}
export enum ORDER_STATUS {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURN_REQUESTED = 'RETURN_REQUESTED',
  RETURNED = 'RETURNED',
}
export enum ORDER_PAYMENT_METHOD {
  ONLINE = 'ONLINE',
  COD = 'COD',
}
export enum ORDER_PAYMENT_STATUS {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  COD_PENDING = 'COD_PENDING',
  REFUNDED = 'REFUNDED',
}
export enum NOTIFICATION_TYPE {
  BOOKING = 'BOOKING',
  PAYMENT = 'PAYMENT',
  PAYOUT = 'PAYOUT',
  BOOKING_STATUS = 'BOOKING_STATUS',
  SYSTEM = 'SYSTEM',
}
export enum OTP_TYPE {
  USER_REGISTRATION = 'USER_REGISTRATION',
  RESET_PASSWORD = 'RESET_PASSWORD',
  RESEND_OTP = 'RESEND_OTP',
}
export enum PAYMENT_METHOD {
  UPI = 'UPI',
  CARD = 'CARD',
  NETBANKING = 'NETBANKING',
  WALLET = 'WALLET',
  BANK_TRANSFER = 'BANK_TRANSFER',
}
export enum PAYMENT_STATUS {
  CREATED = 'CREATED',
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}
export enum PAYMENT_TYPE {
  BOOKING_PAYMENT = 'BOOKING_PAYMENT',
  PUROHIT_PAYOUT = 'PUROHIT_PAYOUT',
  CUSTOMER_REFUND = 'CUSTOMER_REFUND',
  DONATION = 'DONATION',
}
export enum PLATFORM_SETTING_KEY {
  PLATFORM_NAME = 'platform_name',
  SUPPORT_EMAIL = 'support_email',
  SUPPORT_PHONE = 'support_phone',
  COMMISSION_PERCENTAGE = 'commission_percentage',
  GST_PERCENTAGE = 'gst_percentage',
  MAINTENANCE_MODE = 'maintenance_mode',
  PRIVACY_POLICY_URL = 'privacy_policy_url',
  TERMS_AND_CONDITIONS_URL = 'terms_and_conditions_url',
  FACEBOOK_URL = 'facebook_url',
  INSTAGRAM_URL = 'instagram_url',
  YOUTUBE_URL = 'youtube_url',
}
export enum PUROHIT_BOOKING_ACTION {
  ACCEPT = 'ACCEPT',
  DISMISS = 'DISMISS',
}
export enum PUROHIT_MEDIA_TYPE {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
}
export enum PUROHIT_MEDIA_VERIFICATION_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
export enum PUROHIT_PAYMENT_METHOD {
  BANK = 'BANK',
  UPI = 'UPI',
}
export enum PUROHIT_VERIFICATION_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
export enum QUALIFICATION {
  SHASTRI = 'SHASTRI',
  ACHARYA = 'ACHARYA',
  VEDPATHI = 'VEDPATHI',
  OTHER = 'OTHER',
}
export enum REVIEW_STATUS {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
}
export enum USER_ROLE {
  CUSTOMER = 'CUSTOMER',
  PUROHIT = 'PUROHIT',
  ADMIN = 'ADMIN',
}
export enum USER_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  REJECTED = 'REJECTED',
  BLOCKED = 'BLOCKED',
  PENDING = 'PENDING',
}
export enum VENUE_TYPE {
  HOME = 'HOME',
  TEMPLE = 'TEMPLE',
  ONLINE = 'ONLINE',
}
